version: '3.7'

services:
  finance-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: finance-bot
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm run auto
