# @host = 192.168.1.200
@host = localhost
@port = 3001

###

GET http://{{host}}:{{port}}/api/stock/total-position

###

POST http://{{host}}:{{port}}/api/stock/asset-value
content-type: application/json

{
    "assetType": "float",
    "value": 100,
    "dryRun": true
}